# Generated by Django 5.1 on 2024-11-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_on_rest',
            field=models.BooleanField(default=False),
        ),
    ]
